import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — DES/NIS",
  description: "How DES/NIS collects, uses, and protects your information.",
  // Self-canonical: without this the page inherits the root layout's
  // canonical ("/"), which tells Google it's a duplicate of the homepage.
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="June 24, 2026">
      <p>
        This Privacy Policy explains how DES/NIS (&ldquo;DES/NIS&rdquo;, &ldquo;we&rdquo;,
        &ldquo;us&rdquo;, or &ldquo;our&rdquo;) collects, uses, and protects information when
        you visit our website or contact us. By using the site or submitting a form, you
        agree to the practices described here.
      </p>
      <p>
        <strong>Who we are:</strong> DES/NIS is operated by Veljko Cvetković PR Agencija za
        računarsko programiranje DESNIS Niš, a sole proprietor (preduzetnik) registered in
        Serbia, with its registered address at Zelengorska 6, floor 2, apt. 9, 18000 Niš,
        Serbia (Company ID / matični broj: 68358779; Tax ID / PIB: 115427960). For any privacy
        questions you can reach us at <a href="mailto:veljko@desnis.com">veljko@desnis.com</a>.
      </p>

      <h2>Information we collect</h2>
      <p>We only collect the information you choose to give us, plus limited technical data:</p>
      <ul>
        <li>
          <strong>Details you submit through our forms</strong> — such as your name, email
          address, phone number (optional), website URL, company name, the service or plan
          you&rsquo;re interested in, your industry and project goals, and any message you send.
        </li>
        <li>
          <strong>Basic usage data</strong> — aggregated, anonymous statistics about how the
          site is used (for example, page views and approximate region), collected through a
          privacy-friendly analytics tool that does not use tracking cookies.
        </li>
      </ul>

      <h2>How we use your information</h2>
      <ul>
        <li>To respond to your inquiry and provide the information or services you request.</li>
        <li>To prepare proposals, estimates, and communicate about a potential project.</li>
        <li>To operate, maintain, and improve our website.</li>
        <li>To comply with legal obligations and protect against misuse or fraud.</li>
      </ul>

      <h2>Cookies and analytics</h2>
      <p>
        We do not use advertising or cross-site tracking cookies. Our analytics are
        cookieless and rely only on aggregated, anonymized data, so we do not build profiles
        about individual visitors.
      </p>

      <h2>How we share information</h2>
      <p>
        We do not sell or rent your personal information. We share it only with service
        providers that help us operate the site, and only as needed to provide the service:
      </p>
      <ul>
        <li>
          <strong>Resend</strong> — delivers the email notifications generated by our contact
          and project forms.
        </li>
        <li>
          <strong>Vercel</strong> — hosts the website and provides the cookieless analytics.
        </li>
      </ul>
      <p>
        We may also disclose information if required by law or to protect our rights, users,
        or the public.
      </p>

      <h2>Data retention</h2>
      <p>
        We keep form submissions for as long as needed to respond to your inquiry and for our
        legitimate business and legal purposes, after which we delete or anonymize them. You
        can ask us to delete your information at any time.
      </p>

      <h2>Security</h2>
      <p>
        We use reasonable technical and organizational measures to protect your information.
        No method of transmission or storage is completely secure, so we cannot guarantee
        absolute security.
      </p>

      <h2>Your rights</h2>
      <p>
        Depending on where you live, you may have the right to access, correct, delete, or
        restrict the use of your personal information, to object to certain processing, and to
        withdraw consent. To exercise any of these rights, email us at{" "}
        <a href="mailto:veljko@desnis.com">veljko@desnis.com</a> and we&rsquo;ll respond within
        a reasonable timeframe.
      </p>

      <h2>International transfers</h2>
      <p>
        We and our service providers may process your information in countries other than your
        own. Where we do, we take steps to ensure it remains protected in line with this
        policy and applicable law.
      </p>

      <h2>Children&rsquo;s privacy</h2>
      <p>
        Our website is intended for business inquiries and is not directed to children. We do
        not knowingly collect personal information from children.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        We may update this Privacy Policy from time to time. When we do, we&rsquo;ll revise the
        &ldquo;Last updated&rdquo; date above. Significant changes will be highlighted on this
        page.
      </p>

      <h2>Contact us</h2>
      <p>
        If you have any questions about this policy or how we handle your information, contact
        us at <a href="mailto:veljko@desnis.com">veljko@desnis.com</a>.
      </p>
    </LegalPage>
  );
}
